// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjYnrijImtCx-Cd_cUURGa3w3atKTi_c',
    appId: '1:463867324918:web:6e8aa52917e5f2bae3bfd7',
    messagingSenderId: '463867324918',
    projectId: 'gluc-safe',
    authDomain: 'gluc-safe.firebaseapp.com',
    storageBucket: 'gluc-safe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPN5PgY1znAjNeRZne8W3wt7MoaqqJkWQ',
    appId: '1:463867324918:android:d857e330e6b50d49e3bfd7',
    messagingSenderId: '463867324918',
    projectId: 'gluc-safe',
    storageBucket: 'gluc-safe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_vPAnmbM5ap7jehXHYJAlIH1Ye5hP7E',
    appId: '1:463867324918:ios:9c83ea2b6087b90ee3bfd7',
    messagingSenderId: '463867324918',
    projectId: 'gluc-safe',
    storageBucket: 'gluc-safe.appspot.com',
    iosClientId:
        '463867324918-rdv2ripo7t35lttt804ekfd5ob9pscuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.glucSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE_vPAnmbM5ap7jehXHYJAlIH1Ye5hP7E',
    appId: '1:463867324918:ios:9c83ea2b6087b90ee3bfd7',
    messagingSenderId: '463867324918',
    projectId: 'gluc-safe',
    storageBucket: 'gluc-safe.appspot.com',
    iosClientId:
        '463867324918-rdv2ripo7t35lttt804ekfd5ob9pscuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.glucSafe',
  );
}
